// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v6.31.1
// source: categorization.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	CategorizationService_Categorize_FullMethodName = "/ml.CategorizationService/Categorize"
)

// CategorizationServiceClient is the client API for CategorizationService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// CategorizationService предоставляет сервис для автоматической категоризации транзакций
type CategorizationServiceClient interface {
	// Categorize определяет категорию для транзакции на основе описания
	Categorize(ctx context.Context, in *CategorizeRequest, opts ...grpc.CallOption) (*CategorizeResponse, error)
}

type categorizationServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewCategorizationServiceClient(cc grpc.ClientConnInterface) CategorizationServiceClient {
	return &categorizationServiceClient{cc}
}

func (c *categorizationServiceClient) Categorize(ctx context.Context, in *CategorizeRequest, opts ...grpc.CallOption) (*CategorizeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CategorizeResponse)
	err := c.cc.Invoke(ctx, CategorizationService_Categorize_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CategorizationServiceServer is the server API for CategorizationService service.
// All implementations must embed UnimplementedCategorizationServiceServer
// for forward compatibility.
//
// CategorizationService предоставляет сервис для автоматической категоризации транзакций
type CategorizationServiceServer interface {
	// Categorize определяет категорию для транзакции на основе описания
	Categorize(context.Context, *CategorizeRequest) (*CategorizeResponse, error)
	mustEmbedUnimplementedCategorizationServiceServer()
}

// UnimplementedCategorizationServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedCategorizationServiceServer struct{}

func (UnimplementedCategorizationServiceServer) Categorize(context.Context, *CategorizeRequest) (*CategorizeResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Categorize not implemented")
}
func (UnimplementedCategorizationServiceServer) mustEmbedUnimplementedCategorizationServiceServer() {}
func (UnimplementedCategorizationServiceServer) testEmbeddedByValue()                               {}

// UnsafeCategorizationServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CategorizationServiceServer will
// result in compilation errors.
type UnsafeCategorizationServiceServer interface {
	mustEmbedUnimplementedCategorizationServiceServer()
}

func RegisterCategorizationServiceServer(s grpc.ServiceRegistrar, srv CategorizationServiceServer) {
	// If the following call panics, it indicates UnimplementedCategorizationServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&CategorizationService_ServiceDesc, srv)
}

func _CategorizationService_Categorize_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CategorizeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CategorizationServiceServer).Categorize(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CategorizationService_Categorize_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CategorizationServiceServer).Categorize(ctx, req.(*CategorizeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// CategorizationService_ServiceDesc is the grpc.ServiceDesc for CategorizationService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var CategorizationService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "ml.CategorizationService",
	HandlerType: (*CategorizationServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Categorize",
			Handler:    _CategorizationService_Categorize_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "categorization.proto",
}
