// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.31.1
// source: categorization.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// CategorizeRequest запрос на категоризацию
type CategorizeRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Описание транзакции (например, "ПЯТЁРОЧКА МАГАЗИН 2547")
	Description string `protobuf:"bytes,1,opt,name=description,proto3" json:"description,omitempty"`
	// Сумма транзакции (используется для дополнительной классификации)
	Amount float32 `protobuf:"fixed32,2,opt,name=amount,proto3" json:"amount,omitempty"`
	// Валюта транзакции (RUB, USD, EUR)
	Currency      string `protobuf:"bytes,3,opt,name=currency,proto3" json:"currency,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CategorizeRequest) Reset() {
	*x = CategorizeRequest{}
	mi := &file_categorization_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CategorizeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CategorizeRequest) ProtoMessage() {}

func (x *CategorizeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_categorization_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CategorizeRequest.ProtoReflect.Descriptor instead.
func (*CategorizeRequest) Descriptor() ([]byte, []int) {
	return file_categorization_proto_rawDescGZIP(), []int{0}
}

func (x *CategorizeRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *CategorizeRequest) GetAmount() float32 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *CategorizeRequest) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

// CategorizeResponse ответ с результатом категоризации
type CategorizeResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// ID категории
	CategoryId int32 `protobuf:"varint,1,opt,name=category_id,json=categoryId,proto3" json:"category_id,omitempty"`
	// Название категории (например, "Продукты")
	CategoryName string `protobuf:"bytes,2,opt,name=category_name,json=categoryName,proto3" json:"category_name,omitempty"`
	// Уверенность модели (0.0 - 1.0)
	Confidence    float32 `protobuf:"fixed32,3,opt,name=confidence,proto3" json:"confidence,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CategorizeResponse) Reset() {
	*x = CategorizeResponse{}
	mi := &file_categorization_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CategorizeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CategorizeResponse) ProtoMessage() {}

func (x *CategorizeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_categorization_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CategorizeResponse.ProtoReflect.Descriptor instead.
func (*CategorizeResponse) Descriptor() ([]byte, []int) {
	return file_categorization_proto_rawDescGZIP(), []int{1}
}

func (x *CategorizeResponse) GetCategoryId() int32 {
	if x != nil {
		return x.CategoryId
	}
	return 0
}

func (x *CategorizeResponse) GetCategoryName() string {
	if x != nil {
		return x.CategoryName
	}
	return ""
}

func (x *CategorizeResponse) GetConfidence() float32 {
	if x != nil {
		return x.Confidence
	}
	return 0
}

var File_categorization_proto protoreflect.FileDescriptor

const file_categorization_proto_rawDesc = "" +
	"\n" +
	"\x14categorization.proto\x12\x02ml\"i\n" +
	"\x11CategorizeRequest\x12 \n" +
	"\vdescription\x18\x01 \x01(\tR\vdescription\x12\x16\n" +
	"\x06amount\x18\x02 \x01(\x02R\x06amount\x12\x1a\n" +
	"\bcurrency\x18\x03 \x01(\tR\bcurrency\"z\n" +
	"\x12CategorizeResponse\x12\x1f\n" +
	"\vcategory_id\x18\x01 \x01(\x05R\n" +
	"categoryId\x12#\n" +
	"\rcategory_name\x18\x02 \x01(\tR\fcategoryName\x12\x1e\n" +
	"\n" +
	"confidence\x18\x03 \x01(\x02R\n" +
	"confidence2T\n" +
	"\x15CategorizationService\x12;\n" +
	"\n" +
	"Categorize\x12\x15.ml.CategorizeRequest\x1a\x16.ml.CategorizeResponseB<Z:github.com/gibbon/finace-dashboard/internal/grpc_client/pbb\x06proto3"

var (
	file_categorization_proto_rawDescOnce sync.Once
	file_categorization_proto_rawDescData []byte
)

func file_categorization_proto_rawDescGZIP() []byte {
	file_categorization_proto_rawDescOnce.Do(func() {
		file_categorization_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_categorization_proto_rawDesc), len(file_categorization_proto_rawDesc)))
	})
	return file_categorization_proto_rawDescData
}

var file_categorization_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_categorization_proto_goTypes = []any{
	(*CategorizeRequest)(nil),  // 0: ml.CategorizeRequest
	(*CategorizeResponse)(nil), // 1: ml.CategorizeResponse
}
var file_categorization_proto_depIdxs = []int32{
	0, // 0: ml.CategorizationService.Categorize:input_type -> ml.CategorizeRequest
	1, // 1: ml.CategorizationService.Categorize:output_type -> ml.CategorizeResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_categorization_proto_init() }
func file_categorization_proto_init() {
	if File_categorization_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_categorization_proto_rawDesc), len(file_categorization_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_categorization_proto_goTypes,
		DependencyIndexes: file_categorization_proto_depIdxs,
		MessageInfos:      file_categorization_proto_msgTypes,
	}.Build()
	File_categorization_proto = out.File
	file_categorization_proto_goTypes = nil
	file_categorization_proto_depIdxs = nil
}
